API_PREFIX = "/api/v1/ml"
API_KEY_NAME = "X-API-Key"
AVAILABLE_MODELS = ["development", "staging", "production", "experimental", "benchmark"]
PARAMETER_FILE = "parameters.yaml"
KEYWORD_FOLDER = "KeywordClassifier"
KEYWORD_SAMPLE_FILE = "keyword_sample.pkl"
KEYWORD_LABEL_FILE = "keyword_label.pkl"
FILTER_PREPROCESSED_FILE = "filter_preprocessed.pkl"
FILTER_FOLDER = "DataDeliveryModeFilter"
CACHED_RAW_DATA = "raw_data.pkl"
RECORDS_ENHANCED_SCHEMA = "records_enhanced_schema.json"
CONCEPT_AI_DESCRIPTION = "This is the prediction provided by AI model."
# health status file served by Nginx in Docker, see ddai_site.conf
HEALTH_JSON = "/tmp/status/health.json"
STATUS_UP = "UP"
STATUS_STARTING = "STARTING"
STATUS_DOWN = "DOWN"
