[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0
childlogdir=/tmp

[program:app]
command=uvicorn data_discovery_ai.server:app --host 127.0.0.1 --port 9000 --log-config log_config.yaml --workers 1 --timeout-keep-alive 900
directory=/app
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:nginx]
command=/bin/bash -c "until nc -z localhost 9000; do echo 'Waiting for Python app...'; sleep 1; done; echo 'Python app ready! Starting Nginx.'; exec nginx -g 'daemon off;'"
directory=/app
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stopsignal=QUIT
