name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'notebooks/**'
      - 'extras/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: 'latest'
      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install
      - name: Set up environment variables
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        shell: bash
      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files
      - name: Run tests
        run: |
          poetry run pytest
